### PR TITLE
fix(connector): gracefully end data socket

### PR DESCRIPTION
**Pull request by Johnnyrook777**
Fixes GnuTLS error -110: The TLS connection was non-properly terminated issue

### CODE REVIEW

**Comment by Johnnyrook777** [comment]
See #116 for fix

**Comment by trs** [comment]
Great fix!
We can simplify this since `.end()` returns the socket.
```js
this.dataSocket.end().destroy();
```

If you can make this change and rename the commit message to follow the [Angular commit guidelines](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/edit) per the [Contribution guide](https://github.com/trs/ftp-srv/blob/master/CONTRIBUTING.md), eg: `fix(connector): gracefully end data socket`

**Comment by Johnnyrook777** [comment]
Thanks @trs. I'll have to start using those commit conventions more. Thanks for the feedback

**Comment by trs** [comment]
For sure, the reason I use it is that it allows for automatic versioning, tagging, and releasing with `semantic-release`. Releases are easy and automated with CI.

**Pull request merged**
