### PR TITLE
fix: Fixed passive mode address when connecting from localhost

### PR DESCRIPTION
**Pull request by DieMaking**

### CODE REVIEW

**Comment by trs** [comment]
I'd rather see this expanded into if blocks instead of ternary operators.
And a function to test if a given IP is "local" would make it clear.

```js
function isLocalIP(ip) {
  return ip === '127.0.0.1' || ip === 'localhost' || ip == '::1'
}

...

let address = this.server.options.pasv_url;
if (isLocalIP(this.ip)) {
  address = this.ip;
}
```

**Comment by DieMaking** [comment]
I think that IP can never be `localhost` because it's hostname. So it can be done like that:
```
function isLocalIP(ip) {
  return ip === '127.0.0.1' || ip == '::1';
}

...

let address = (isLocalIP(this.ip) ? this.ip : this.server.options.pasv_url);
// or
let address = this.server.options.pasv_url;
if (isLocalIP(this.ip)) {
  address = this.ip;
}
```
or maybe make pasv_url option as callback called every time when someone sends PASV command to the server? Connected user's IP will be passed to the callback parameters and server developer will handle connecting from localhost by itself.

**Comment by trs** [comment]
If there becomes a need to make it a callback it can be. The only reason I see to make it a callback would be for this exact case.

That looks good to me. I'd rather the `if` block only because it's clearer to me at a glance.

**Comment by trs** [comment]
That method can go in https://github.com/trs/ftp-srv/tree/master/src/helpers

**Comment by trs** [comment]
Added to: https://github.com/trs/ftp-srv/pull/168

**Pull request closed without merging**
