### PR TITLE
fix: make securecontext compliant

### PR DESCRIPTION
**Pull request by TimLuq**
The readme specifies that the `tls` option is a "TLS secure context object", which is ambiguous if this is the an instance of `SecureContext` or if it is the options object. This is now explicitly stated and the typings reflect this which were previously wrong.

It is still a lie to say that it is a `SecureContextOptions` since the fields `ca`, `cert`, and `key` are always treated as file names and read synchronously if they are set. There is now a way to opt-out of this behavior since it is to late to make it opt-in. One opts-in by adding `isContextCompliant: true` to the object, which is now presented in the readme.

### CODE REVIEW

**Comment by trs** [comment]
This bug is definitely valid, but I don't think this is the right way to solve this. I'd rather not introduce new options specific to the package for TLS options.
I think this could be solved by checking if the options are already buffers or if they are strings (file paths).

**Comment by TimLuq** [comment]
I thought of that as well, but `createSecureContext` expects strings to be in PEM format - not file paths. So without breaking implementations already using file paths there is no way to use a non-extended version of `SecureContextOptions`. This way the same object works in either case since it is disregarded by other functions creating `SecureContext`s.

I guess using an exported symbol instead of a string key for the property would be better since it will never be a conflict, but then it would be impossible to read from or serialize to JSON.

**Comment by trs** [comment]
I see what you mean. `createSecureContext` is already expecting the PEM formatted key, not a path to one.
We could check if the string is a file path, and read it that way, otherwise just pass it through?

**Comment by TimLuq** [comment]
That is a possibility, though detecting file paths without resorting to `fs.statSync` or trying to `fs.readFileSync` and checking for `ENOENT` or filepath length errors is bit of a chore. I really don't like doing synchronous IO when failure is the expected result.

If we check for a valid file using `fs.*Sync` this would throw if it is a PEM key or if there is a typo in the filepath. If we expect failure to be the first case the typo would probably get an error similar to "key data too short" which may be hard for users to understand.

Also: Though few people use the feature is it is valid to express a file path as one of `string | Buffer | URL | integer` for `readFile`, which would break if we'd just check for `typeof x === "string"`. Checking filenames in `Buffer`s is even harder than in string since the system encoding might be different from utf8.

If you believe something along these lines is the right way to go I would be fine with it - although I would not be bursting with joy.
```js
/**
 * Returns data: Tries to open data as a filename and return content,
 * fall back to data if file does not exist.
 *
 * @param {string | object} data filename as a string or data as Buffer, string, or object
 * @returns {string | object} data as Buffer, string, or object
 */
fileOrData(data) {
    if (typeof data === "object" && !(data instanceof Buffer || data instanceof URL)) {
        // the `{ pem: "XYZ", passphrase: "123" }` data is never a file
        return data;
    }
    try {
        // will throw if path error or if file does not exist
        return fs.readFileSync(data);
    } catch (e) {
        if (typeof data === "number" || (typeof data === "object" && data instanceof URL)) {
            throw e;
        }
        // TODO: e should probably be rethrown in a few other cases
        return data;
    }
}
```

**Comment by trs** [comment]
Great post, it's a much more difficult problem than I thought initially.

With the next release being a breaking change (`3.0.0`) I think I'll change this so it implements the actual `SecureContext` options. This solves this conundrum.

**Comment by trs** [comment]
https://github.com/trs/ftp-srv/pull/112

**Pull request closed without merging**
