### PR TITLE
fix: reject on listen error, listen on hostname

### PR DESCRIPTION
**Pull request by trs**
Thanks to @TimLuq (https://github.com/trs/ftp-srv/pull/85)

### CODE REVIEW

**Comment by trs** [comment]
@TimLuq I can see some impacts with the hostname fix.

Because it wasn't specific, it would listen on all available addresses (`0.0.0.0`), so this might break some builds.

I'll do some further testing before pulling this into master.

**Comment by TimLuq** [comment]
Yes, when I saw that the checks failed I did a quick skim through the test cases and assumed that the tests were incomplete in this regard.

Since the new behavior is the one previously documented most dependents should probably have correct `listen` calls. But there are sure to be some that are not.

Perhaps releasing this fix under a new minor version instead of a patch? Although that is technically bad practice. But so is breaking projects with a patch update. (Also with a minor update, but since it follows both the documented and intended behavior it could be done.) Tough call.

**Comment by TimLuq** [comment]
This could also be seen as a security patch since users who are not behind a firewall and have configured what they believe to be a localhost-only server currently accepts external connections. Maybe they have given full filesystem access to an anonymous connection as they assume only localhost may establish connections.

**Comment by trs** [comment]
I think I will release this as a breaking change, so a new major version. It has a chance of breaking some peoples usages, so it's the safest way to release this change.

**Comment by trs** [comment]
Looking at others that are using `ftp-srv`, I don't believe this will have any negative impacts on their projects. I think a minor version will suffice.

**Pull request merged**
